Classified.create(title: 'Whitecaps Tickets', description: 'Section 46, row C, seats 1 and 2')
Classified.create(title: 'Bike Trailer', description: 'Chariot Cougar 2, in good condition')
Classified.create(title: 'iPhone 4', description: 'iPhone 4, 32G, white, no scratches')
Classified.create(title: 'Mountain Bike', description: 'Brodie Bruzza 2012')
Classified.create(title: 'Star Wars Blu-ray', description: 'The complete sage, 6 movies')
